Работаем с датой
htmlacademy-php/1260839-yeticave-12 pull request #6
Opened 2021-06-11 13:23 UTC by niniklic

исправлены замечания с прошлого задания,
добавлена функция по подсчету времени до истечения лота,
в случае если осталось меньше часа до истечения, диву добавляется класс для стилизации

2021-06-11 14:34 UTC, VikingBO requested changes
В целом супер, только немного подправить :)

2021-06-11 14:34 UTC, VikingBO commented on index.php
> +    $diffDate = date_create($expire_date)->getTimestamp() - date_create(date("Y-m-d h:i"))->getTimestamp();
Отлично что решили попробовать `date_create()`, есть ещё функция [`date_diff()`](https://www.php.net/manual/ru/datetime.diff.php), пробовали её?

2021-06-11 14:34 UTC, VikingBO commented on index.php
> +    if ($diffDate <= 0) {
Мы можем опустить эту проверку и сделать значение `$leftTimeArray` с нулевыми данными в массиве значение по умолчанию, а чуть ниже проверять является ли разница положительной и тогда уже менять на нужные значения.

2021-06-11 14:34 UTC, VikingBO commented on templates/main.php
> +                        <div class="lot__timer timer <?php if (time_left($advertItem['expireDate'])['hours'] < 1): ?>timer--finishing<?php endif; ?>">
Не очень красиво получается когда мы для каждого значения делаем запрос в функцию тем более что ответ во всех трёх случаях у нас будет идентичный, лучше вынести вызов в инициализацию переменной и потом просто использовать эту переменную в подстановке и проверках.

2021-06-11 14:41 UTC, niniklic commented on index.php
> +    if ($diffDate <= 0) {
да, действительно, это гораздо проще и логичней)))

2021-06-15 13:09 UTC, VikingBO approved these changes
Всё отлично

2021-06-15 13:09 UTC, merged